# spring
spring:
  datasource:
    url: jdbc:mysql://124.220.14.106:3306/thirdlib
    username: thirdlib
    password: C8C061C3A18D8E63BBB811E47A67696C
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialize: true
  sql:
    init.continue-on-error: true
  config:
    additional-location: classpath:/lib/
  web.resources.static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:temp/tpls/upload/

server:
  session:
    cookie:
      secure: false
# 日志
logging.level:
  root: INFO
  org.springframework.web: DEBUG
  com.myapp: DEBUG

# ??????????
myapp.custom.property: value

# 文件上传
file:
  # 服务器上的地址 localhost:8080/upload
  staticAccessPath: /upload/
  # 本地路径 /tmp/tpls/upload
  uploadFolder: /tmp/tpls/upload/
  # uploadFolder: D:/tmp/tpls/upload/
  webPagePath: /public/
  webPageFolder: /tmp/tpls/public/


